name: 'Unit tests'

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build & test
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v1

      - name: Install npm dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Run unit tests
        run: |
          yarn test
